### ISSUE TITLE
[Feature Suggestion] Add fetched lyrics to the file metadata

### ISSUE THREAD

**Issue by sasuketobi** [geecko86/QuickLyric#78] opened 2015-05-05 10:22 UTC
Is it possible to add the fetched lyrics to the mp3 file, in the tags, after confirmation from the user to save lyrics to file? I've seen that the lyrics can be embedded to the mp3 file itself, this would be a very handy feature in case the mobile data isn't available.

**Comment by geecko86** [comment] 2015-05-05 10:26
Yes, that is scheduled. Thanks for filing an issue. This is however, a duplicate of #75.

**Closed by geecko86** 2015-05-05 10:26 UTC
