### ISSUE TITLE
Add MusicID service Track ID

### ISSUE THREAD

**Issue by Wabuo** [geecko86/QuickLyric#189] opened 2017-03-28 22:15 UTC
I would love if QuickLyric would be able to import songs from [Track ID](https://play.google.com/store/apps/details?id=com.sonyericsson.trackid) a service like Shazam.

**Comment by geecko86** [comment] 2017-03-28 22:19
Duplicate of #188

Please try to search it before you open an issue. 🙃

**Closed by geecko86** 2017-03-28 22:19 UTC

**Comment by geecko86** [comment] 2017-03-28 22:21
Wait, I read your post too fast.

Actually, #188 will make importing songs from MusicID services irrelevant, so I don't think we will implement support for TrackID.

**Comment by Wabuo** [comment] 2017-03-28 22:48
@geecko86 Din't you close #188 because its impossible right now with no open API available?

**Comment by geecko86** [comment] 2017-03-28 22:57
No, it's not closed. I have something in mind.
